### ISSUE TITLE
如何开启不能说的功能

### ISSUE THREAD

**Issue by LittleRey** [lz233/FuckCoolapk#4]
如何开启不能说的功能

**Comment by JiZhi-Error** [comment]
找页面布局，有个隐藏的按钮

**Comment by JiZhi-Error** [comment]
> 如何开启不能说的功能

找页面布局，有个隐藏按钮

**Comment by LittleRey** [comment]
是在插件里面找还是酷安里面找按钮

**Comment by JiZhi-Error** [comment]
> 是在插件里面找还是酷安里面找按钮

模块里找

**Comment by LittleRey** [comment]
是不是需要解包重新写布局，

**Comment by JiZhi-Error** [comment]
> 是不是需要解包重新写布局，

这都开源了，你直接改visibility啊

**Comment by BoBppy** [comment]
没什么意义

**Comment by tpnet** [comment]
在Android/data/com.fuckcoolapk/files 里面新增一个adminMode.txt文件，内容是true。 就可以开启管理员模式了，但是没啥用，例如上推荐上头条什么的，服务器有用户验证的，改本地没啥用。
