### ISSUE TITLE
不适配11.0正式版了嘛（ '▿ ' ）

### ISSUE THREAD

**Issue by Jonekadsen** [lz233/FuckCoolapk#9]

**Comment by MlgmXyysd** [comment]
我要期末考试，鱼鱼跟我一样都高二，应该也期末考试

**Comment by lz233** [comment]
过几天考虑用 kotlin 重写。

**Comment by MlgmXyysd** [comment]
> 过几天考虑用 kotlin 重写。

Kotlin，屑哎

**Comment by lz233** [comment]
nmsl2021年1月26日 下午11:53，Jim Wu <notifications@github.com>寫道：



过几天考虑用 kotlin 重写。



Kotlin，屑哎
